#!/bin/sh                                                                                                                                       
                                                                                                                                                
(                                                                                                                                               
sleep 1                                                                                                                                         
                                                                                                                                                
echo "login serveradmin $SERVERADMINPASSWORD"                                                                                                               
                                                                                                                                                
sleep 1                                                                                                                                         
                                                                                                                                                
echo "use 1"                                                                                                                                    
                                                                                                                                                
sleep 1                                                                                                                                         
                                                                                                                                                
echo "serversnapshotcreate"                                                                                                                     
                                                                                                                                                
sleep 3                                                                                                                                         
                                                                                                                                                
echo "quit"                                                                                                                                     
                                                                                                                                                
) | telnet 192.168.1.1 10011 > /mnt/output.txt                                                                                                 
                                                                                                                                                
grep "data" /mnt/output.txt | tee /mnt/serverHash-$(date +"%Y%m%d").txt > /mnt/ts3ServerBackupOnDocker/serverHash                               
                                                                                                                                                
sleep 1                                                                                                                                         
                                                                                                                                                
cd /mnt/ts3ServerBackupOnDocker                                                                                                                 
                                                                                                                                                
sleep 1                                                                                                                                         
                                                                                                                                                
git add serverHash                                                                                                                              
                                                                                                                                                
sleep 1                                                                                                                                         
                                                                                                                                                
git commit -m "$(date +"%Y%m%d-%H%M%S")"                                                                                                        
                                                                                                                                                
sleep 2                                                                                                                                         
                                                                                                                                                
git push origin 2>&1
